version: "3.6"

services:
    nft-app:
        container_name: nft-app
        image: nikolaik/python-nodejs:python3.7-nodejs16-alpine
        restart: always
        env_file: .env
        volumes:
            - ./:/src
        working_dir: /src
        ports:
            - 3000:3000
            - 8545:8545
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command:
            - /bin/sh
            - -c
            - |
                npm i
                npm run dev